name: Test dd-trace-rb compilation

on:
  push:
  pull_request:
  workflow_call:
  workflow_dispatch:

jobs:
  test-compilation:
    runs-on: ubuntu-latest
    name: "Ruby:${{ matrix.ruby_version }}"
    strategy:
      fail-fast: false
      matrix:
        include:
          # We want to test all variants shipped under lib/datadog/ruby_core_source,
          # and the last Ruby version the variant can be used with.
          # So we test all variant versions, all major.minor, and all variant versions with patch-1
          - { ruby_version: '2.5.0' } # Uses own headers
          - { ruby_version: '2.5.1' } # Uses own headers
          - { ruby_version: '2.5.3' } # Last version using 2.5.1 headers
          - { ruby_version: '2.5.4' } # Uses own headers
          - { ruby_version: '2.5'   } # Last version using 2.5.4 headers
          - { ruby_version: '2.6.0' } # Uses own headers
          - { ruby_version: '2.6'   } # Last version using 2.6.0 headers
          - { ruby_version: '2.7.0' } # Uses own headers
          - { ruby_version: '2.7'   } # Last version using 2.7.0 headers
          - { ruby_version: '3.0.0' } # Uses own headers
          - { ruby_version: '3.0'   } # Last version using 3.0.0 headers
          - { ruby_version: '3.1.0' } # Uses own headers
          - { ruby_version: '3.1'   } # Last version using 3.1.0 headers
          - { ruby_version: '3.2.0' } # Uses own headers
          - { ruby_version: '3.2'   } # Last version using 3.2.0 headers
          - { ruby_version: '3.3.0' } # Uses own headers
          - { ruby_version: '3.3.4' } # Last version using 3.3.0 headers
          - { ruby_version: '3.3.5' } # Uses own headers
          - { ruby_version: '3.3'   } # Last version using 3.3.5 headers
          - { ruby_version: '3.4.0' } # Uses own headers
          - { ruby_version: '3.4'   } # Last version using 3.4.0 headers
          - { ruby_version: '4.0.0' } # Uses own headers
          - { ruby_version: '4.0.5' } # Last version using 4.0.0 headers
          - { ruby_version: '4.0.6' } # Uses own headers
          - { ruby_version: '4.0'   } # Last version using 4.0.6 headers

    steps:
      - uses: ruby/setup-ruby@95ef2b042f9d7a56d8268cba8559e2842e2ad01b # v1.321.0
        with:
          ruby-version: ${{ matrix.ruby_version }}
          bundler: latest
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          path: datadog-ruby_core_source
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          repository: Datadog/dd-trace-rb
          path: dd-trace-rb
      - name: Add datadog-ruby_core_source
        working-directory: ./dd-trace-rb
        run: |
          bundle add datadog-ruby_core_source --path=../datadog-ruby_core_source
          bundle info datadog-ruby_core_source

      - name: Compile and validate it works
        working-directory: ./dd-trace-rb
        run: bundle exec rake compile

      - run: bundle exec rake clean
        working-directory: ./dd-trace-rb

      # "Corruption" tests validate that missing a file really breaks compilation (and thus our tests are working)
      - name: Corrupt the sources
        run: rm -v  lib/datadog/ruby_core_source/*/iseq.h
        working-directory: ./datadog-ruby_core_source

      - name: Compile and validate it fails
        working-directory: ./dd-trace-rb
        run: |
          if bundle exec rake compile; then
            echo "❌ Expected failure but got success (exit code 0)"
            exit 1
          else
            echo "✅ Got expected failure"
          fi
